### ISSUE TITLE
`/etc/php/7.3/apache2/php.ini' not recognized

### ISSUE THREAD

**Issue by Entretoize** [krakjoe/tombs#13]
I'm trying to build tombs with :
`./configure /etc/php/7.3/apache2/php.ini`
but it fails with the following errors:
```
checking build system type... Invalid configuration `/etc/php/7.3/apache2/php.ini': machine `/etc/php/7.3/apache2/php.ini' not recognized
configure: error: /bin/bash build/config.sub /etc/php/7.3/apache2/php.ini failed
root@creforma:~/tombs# ./configure /etc/php/7.3/apache2/php.ini

```

**Comment by krakjoe** [comment]
You have the command wrong, see `./configure --help`

**Comment by Entretoize** [comment]
I do: `./configure --with-php-config=/etc/php/7.4/apache2/php.ini`

It gives:
`configure: error: Cannot find php-config. Please use --with-php-config=PATH`
But this what I'm doing !

**Comment by Entretoize** [comment]
Ok, I've found my mistake, and been able to build.
I added the zend_extension=tombs.so but the php -v only write about opcache, do I need to move tombs.so somewhere and/or add the absolute path ?

**Comment by Entretoize** [comment]
?
