### ISSUE TITLE
How to connect to socker?

### ISSUE THREAD

**Issue by Spartaques** [krakjoe/tombs#6]
I'm installed extension but have not any idea how to connect to socker? Need help)

**Comment by MattyRad** [comment]
I had the same question, the tests provide some decent examples https://github.com/krakjoe/tombs/blob/develop/tests/zend_tombs.inc, https://github.com/krakjoe/tombs/blob/develop/tests/001.phpt

**Comment by krakjoe** [comment]
Sorry, this is out of the scope of issues.
